version: '3'

services:
  rabbitmq: #  guest/guest https://mindbyte.nl/2018/04/05/run-rabbitmq-using-docker-compose-with-guest-user.html
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
#    volumes:
#      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

